export enum API_METHOD {
  ADVANCED_SEARCH = "advancedSearch",
  GET_CACHING_NODES = "getCachingNodes",
  GET_CHANGES = "getChanges",
  GET_FEED = "getFeed",
  GET_GENRES = "getGenres",
  GET_RANDOM_TITLE = "getRandomTitle",
  GET_RSS = "getRSS",
  GET_SCHEDULE = "getSchedule",
  GET_SEED_STATS = "getSeedStats",
  GET_TITLE = "getTitle",
  GET_TITLES = "getTitles",
  GET_TEAM = "getTeam",
  GET_UPDATES = "getUpdates",
  GET_YEARS = "getYears",
  GET_YOUTUBE = "getYouTube",
  SEARCH_TITLES = "searchTitles",
  GET_FAVORITES = "getFavorites",
  DEL_FAVORITES = "delFavorites",
  ADD_FAVORITES = "addFavorites",
}
