export enum MOD_ERR {
  TIMEOUT_HAS_EXPIRED = "TIMEOUT_HAS_EXPIRED",
  RELEASE_NOT_FOUND = "RELEASE_NOT_FOUND",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  WRONG_PASSWD = "WRONG_PASSWD",
  NET_ERROR = "NET_ERROR",
  INVALID_USER = "INVALID_USER",
  REQUIRED_PARAM_IS_EMPTY = "REQUIRED_PARAM_IS_EMPTY",
}
