export enum API_METHOD_PATH {
  GET_TITLE = "getTitle",
  GET_TITLE_LIST = "title/list",
  GET_TITLE_UPDATES = "title/updates",
  GET_TITLE_CHANGES = "title/changes",
  GET_TITLE_SCHEDULE = "title/schedule",
  GET_TITLE_RANDOM = "title/random",
  GET_TITLE_SEARCH = "title/search",
  GET_TITLE_SEARCH_ADVANCED = "title/search/advanced",
  GET_TITLE_FRANCHISES = "title/franshises",
  GET_YOUTUBE = "youtube",
  GET_FEED = "feed",
  GET_YEARS = "years",
  GET_GENRES = "genres",
  GET_TEAM = "team",
  GET_TORRENT_SEED_STATS = "torrent/seed_stats",
  GET_TORRENT_RSS = "torrent/rss",
  GET_FRANCHISE_LIST = "franchise/list",
  GET_USER = "user",
  ALL_USER_FAVORITES = "user/favorites",
}
